[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "upgrade-insecure-requests"
    Strict-Transport-Security = "max-age=86400, includeSubDomains"
    referrer-policy = "same-origin"
    permissions-policy = "geolocation=(self)"
    X-Content-Type-Options = "nosniff"
